[package]
name = "gaussian-backend"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
spark-lib = { path = "../vendor/spark-lib", default-features = false, features = ["gsplat", "ply", "spz", "antisplat", "ksplat", "sogs", "rad", "tiny_lod"] }
anyhow.workspace = true
ahash.workspace = true
glam.workspace = true
smallvec.workspace = true
ordered-float.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
serde-wasm-bindgen.workspace = true

[lints]
workspace = true

[dev-dependencies]
image.workspace = true
zip.workspace = true
